---
title: "2023-04-24-geom-circlepack-collapse"
author: "Evangeline Reynolds"
date: "4/24/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggcirclepack)
library(tidyverse)
tidytitanic::passengers %>% 
  ggplot() +
  aes(id = name %>% as.factor()) + 
  geom_polygon_circlepack() + 
  aes(fill = sex) + 
  aes(area = age) + 
  labs(title = "ages varied on the titanic") +
  aes(alpha = survived)

# but counting is cool
tidytitanic::passengers %>% 
  count(sex, survived) %>% 
  mutate(row = row_number()) %>% 
  ggplot() +
  aes(id = row) + 
  geom_polygon_circlepack(color = "black") + 
  aes(area = n) + 
  aes(fill = sex) + 
  aes(alpha = survived) + 
  coord_equal()
```


```{r, eval = T}

compute_panel_circle_pack_collapse <- function(data, scales, fun = sum){


  if(is.null(data$area)){

    data %>%
      mutate(area = 1) ->
      data1

  }

  data1 %>%
    group_by(across(c(alpha, fill))) %>%
    summarize(area = sum(area)) %>% 
    ungroup() %>% 
    mutate(id = row_number()) ->
  data_collapsed  
  
  data_collapsed %>% 
    pull(area) %>%
    packcircles::circleProgressiveLayout(
      sizetype = 'area') %>%
    packcircles::circleLayoutVertices(npoints = 300) %>%
    left_join(data_collapsed)

}


tidytitanic::passengers %>% 
  rename(fill = sex, 
         alpha = survived) %>% 
  compute_panel_circle_pack_collapse() %>% 
  head()
```

```{r, eval = T}
StatCirclepackcollapse <- ggplot2::ggproto(`_class` = "StatCirclepackcollapse",
                                  `_inherit` = ggplot2::Stat,
                                  # required_aes = c("id", "linetype"),
                                  compute_panel = compute_panel_circle_pack_collapse,
                                  # setup_data = my_setup_data,
                                  default_aes = ggplot2::aes(group = after_stat(id))
                                  )


#' Title
#'
#' @param mapping
#' @param data
#' @param position
#' @param na.rm
#' @param show.legend
#' @param inherit.aes
#' @param ...
#'
#' @return
#' @export
#'
#' @examples
#' library(ggplot2)
#' library(magrittr)
#' library(dplyr)
#' gapminder::gapminder %>%
#' filter(year == 2002) %>%
#'   ggplot() +
#'   aes(id = continent) +
#'   geom_polygon_circlepack_collapse(alpha = .5, size = .002)
#'
#' last_plot() +
#'   aes(fill = continent)
#'
#' last_plot() +
#'   aes(area = pop)
#'
#' last_plot() +
#'   aes(color = continent) +
#'   facet_wrap(facets = vars(continent))
geom_polygon_circlepack_collapse <- function(mapping = NULL, data = NULL,
                           position = "identity", na.rm = FALSE,
                           show.legend = NA,
                           inherit.aes = TRUE, ...) {
  ggplot2::layer(
    stat = StatCirclepackcollapse, # proto object from Step 2
    geom = ggplot2::GeomPolygon, # inherit other behavior
    data = data,
    mapping = mapping,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(na.rm = na.rm, ...)
  )
}

tidytitanic::passengers %>% 
ggplot() +
  aes(alpha = survived, fill = sex) + 
  geom_polygon_circlepack_collapse(color = "black") +
  coord_equal()
```


```{r}
tidytitanic::passengers %>% 
ggplot() +
  aes(alpha = survived) + 
  geom_polygon_circlepack_collapse(color = "black") +
  coord_equal()
```
